name: flutter assignment
description: A flutter assignment for gigabank

publish_to: 'none'

version: 1.0.0+21

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  reactive_forms: ^14.2.0
  reactive_flutter_typeahead: ^0.8.1
  freezed_annotation: ^2.2.0
  riverpod_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  riverpod_generator:

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
