name: Increment App Version Build

on:
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Increment Build Number
      id: increment-version
      run: |
        # Extract and increment version
        current_version=$(awk '/version:/ {print $2}' pubspec.yaml)
        major=$(echo $current_version | cut -d'.' -f1)
        minor=$(echo $current_version | cut -d'.' -f2)
        patch=$(echo $current_version | cut -d'+' -f1 | cut -d'.' -f3)
        build=$(echo $current_version | cut -d'+' -f2)
        new_build=$((build + 1))
        new_version="$major.$minor.$patch+$new_build"
        sed -i "s/version:[[:space:]]*$current_version/version: $new_version/" pubspec.yaml
        echo "Version updated to $new_version"
        echo "::set-output name=new_version::$new_version"

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Create New Branch
      run: |
        new_branch="version_bump_${{ steps.increment-version.outputs.new_version }}"
        git checkout -b $new_branch

    - name: Commit and Push Changes
      run: |
        git add pubspec.yaml
        git commit -m "Incremented build number to ${{ steps.increment-version.outputs.new_version }}"
        git push -u origin $new_branch
