name: Increment App Version Build

on:
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Increment Build Number
      run: |
        # Extract current version from pubspec.yaml
        current_version=$(awk '/version:/ {print $2}' pubspec.yaml)
        major=$(echo $current_version | cut -d'.' -f1)
        minor=$(echo $current_version | cut -d'.' -f2)
        patch=$(echo $current_version | cut -d'+' -f1 | cut -d'.' -f3)
        build=$(echo $current_version | cut -d'+' -f2)
        new_build=$((build + 1))

        # Update the version
        new_version="$major.$minor.$patch+$new_build"
        sed -i "s/version:[[:space:]]*$current_version/version: $new_version/" pubspec.yaml
        echo "Version updated to $new_version"

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Create New Branch
      run: |
        new_branch="version_bump_$new_version"
        git checkout -b $new_branch

    - name: Commit Changes
      run: |
        git add pubspec.yaml
        git commit -m "Incremented build number to $new_version"

    - name: Push Changes
      run: |
        git push origin $new_branch

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        title: "Version Bump to $new_version"
        body: "This is an automated pull request to update the version number in pubspec.yaml."
        labels: version-bump
        commit-message: "Create PR for version bump to $new_version"

    - name: Merge Pull Request
      if: steps.create-pr.outputs.pull-request-number
      run: |
        pr_number=$(echo ${{ steps.create-pr.outputs.pull-request-number }})
        gh pr merge $pr_number --auto --squash -R ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
