name: Increment App Version Build

on:
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Increment Build Number
      id: increment-version # Add an ID here to reference its outputs later
      run: |
        # Extract and increment version
        current_version=$(awk '/version:/ {print $2}' pubspec.yaml)
        major=$(echo $current_version | cut -d'.' -f1)
        minor=$(echo $current_version | cut -d'.' -f2)
        patch=$(echo $current_version | cut -d'+' -f1 | cut -d'.' -f3)
        build=$(echo $current_version | cut -d'+' -f2)
        new_build=$((build + 1))
        # Update the version
        new_version="$major.$minor.$patch+$new_build"
        sed -i "s/version:[[:space:]]*$current_version/version: $new_version/" pubspec.yaml
        echo "Version updated to $new_version"
        # Configure Git
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        # Create new branch
        new_branch="version_bump_$new_version"
        git checkout -b $new_branch
        # Commit and push changes
        git add pubspec.yaml
        git commit -m "Incremented build number to $new_version"
        git push origin $new_branch
        # Use ::set-output syntax to make new_version and new_branch available for other jobs
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "new_branch=$new_branch" >> $GITHUB_ENV

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Increment build number to ${{ env.new_version }}"
        pr_body: "Automated PR to update build number to ${{ env.new_version }}"
        branch: ${{ env.new_branch }}

# Uncomment and use this part if you want to automatically merge the PR when conditions are met
#    - name: Merge Pull Request
#      uses: pascalgn/automerge-action@v0.16.2
#      with:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        MERGE_LABELS: "automerge"
#        MERGE_METHOD: "squash"
#        MERGE_COMMIT_MESSAGE: "pull-request-title"
#        MERGE_FILTER_AUTHOR: "github-actions[bot]"
