name: Modify File, Commit, PR, and Auto Merge

on:
  workflow_dispatch:

jobs:
  modify_file_commit_create_pr_and_merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Configure git user
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"

      # Generate a unique branch name with timestamp
      - name: Generate unique branch name
        run: echo "BRANCH_NAME=update-dummy-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Create new branch with the unique name
      - name: Create new branch
        run: |
          git branch ${{ env.BRANCH_NAME }}
          git checkout ${{ env.BRANCH_NAME }}

      # Modify dummy.txt file by adding a new line
      - name: Add new line to dummy file
        run: |
          echo "New line added on $(date)" >> lib/dummy.txt
          git add lib/dummy.txt
          git commit -m "Add new line to dummy file"

      # Push the new branch
      - name: Push new branch
        run: git push --set-upstream origin ${{ env.BRANCH_NAME }}

      # Create a pull request and get its number for merging
      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update to Dummy File', // Customize your PR title
              head: process.env.BRANCH_NAME,
              base: 'main', // The name of the branch you want the changes pulled into
              body: 'This PR adds a new line to the dummy file.', // Customize your PR description
              draft: false,
            });

            if (response.status !== 201) {
              throw new Error('Failed to create pull request');
            }

            console.log('Pull request created:', response.data.html_url);

            // Output the PR number for later steps
            return response.data.number;

      # Automatically merge the PR
      - name: Auto Merge PR
        if: steps.create_pr.outputs.result
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.create_pr.outputs.result }}, // Use the PR number from the previous step
              merge_method: 'merge', // Can be merge, squash or rebase
            });
